### ISSUE TITLE
Parsing errors not in either left

### ISSUE THREAD

**Issue by damdev** [alonsodomin/cron4s#327]
```scala
scala> Cron("* * * * *")
java.util.NoSuchElementException: head of empty list
  at scala.collection.immutable.Nil$.head(List.scala:430)
  at scala.collection.immutable.Nil$.head(List.scala:427)
  at cron4s.parsing.CronTokenReader.first(parser.scala:26)
  at cron4s.parsing.CronTokenReader.first(parser.scala:25)
  at cron4s.parsing.BaseParser.handleError(base.scala:25)
  at cron4s.parsing.BaseParser.handleError$(base.scala:24)
  at cron4s.parsing.CronParser$.handleError(parser.scala:32)
  at cron4s.parsing.CronParser$.read(parser.scala:182)
  at cron4s.parsing.package$.$anonfun$parse$1(package.scala:26)
  at scala.util.Either.flatMap(Either.scala:341)
  at cron4s.parsing.package$.parse(package.scala:25)
  at cron4s.Cron$.parse(Cron.scala:50)
  at cron4s.Cron$.apply(Cron.scala:39)
  ... 36 elided
```

This should return a Left with a better Error

**Comment by alessandrovaccaro** [comment]
I see the same issue on `0.6.0`.
